# Generated by Django 4.1 on 2022-10-01 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("credentials", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="movie",),
    ]
